# Generated by Django 5.2.7 on 2025-10-07 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etsy_shop_id', models.CharField(help_text='ID único de la tienda en Etsy', max_length=100, unique=True, verbose_name='ID de Tienda Etsy')),
                ('shop_name', models.CharField(help_text='Nombre de la tienda en Etsy', max_length=255, verbose_name='Nombre de Tienda')),
                ('access_token', models.TextField(help_text='Token de acceso OAuth de Etsy', verbose_name='Access Token')),
                ('refresh_token', models.TextField(help_text='Token de refresco OAuth de Etsy', verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(help_text='Fecha y hora de expiración del access token', verbose_name='Expiración del Token')),
                ('is_active', models.BooleanField(default=True, help_text='Si la tienda está activa para sincronización', verbose_name='Activa')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Si la sincronización automática está habilitada', verbose_name='Sincronización Habilitada')),
                ('sync_interval', models.IntegerField(default=15, help_text='Intervalo de sincronización en minutos', verbose_name='Intervalo de Sincronización')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Fecha y hora de la última sincronización exitosa', null=True, verbose_name='Última Sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('owner', models.ForeignKey(help_text='Usuario dueño de esta tienda', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'ordering': ['-created_at'],
            },
        ),
    ]
