# Generated by Django 5.2.7 on 2025-10-07 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etsy_receipt_id', models.CharField(help_text='ID único del recibo en Etsy', max_length=100, verbose_name='ID de Recibo Etsy')),
                ('buyer_name', models.CharField(help_text='Nombre del comprador', max_length=255, verbose_name='Nombre del Comprador')),
                ('buyer_email', models.EmailField(help_text='Email del comprador', max_length=254, verbose_name='Email del Comprador')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Monto total de la venta', max_digits=10, verbose_name='Monto Total')),
                ('currency', models.CharField(default='USD', help_text='Código de moneda (USD, EUR, etc.)', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', help_text='Estado actual de la orden', max_length=20, verbose_name='Estado')),
                ('sale_date', models.DateTimeField(help_text='Fecha y hora en que se realizó la venta', verbose_name='Fecha de Venta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('store', models.ForeignKey(help_text='Tienda donde se realizó la venta', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stores.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-sale_date'],
                'unique_together': {('store', 'etsy_receipt_id')},
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Cantidad de unidades vendidas', verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10, verbose_name='Precio Unitario')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Precio total del ítem (cantidad * precio unitario)', max_digits=10, verbose_name='Precio Total')),
                ('product', models.ForeignKey(help_text='Producto vendido (puede ser null si se eliminó)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(help_text='Venta a la que pertenece este ítem', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Ítem de Venta',
                'verbose_name_plural': 'Ítems de Venta',
            },
        ),
    ]
