# Generated by Django 5.2.7 on 2025-10-07 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etsy_listing_id', models.CharField(help_text='ID único del listing en Etsy', max_length=100, verbose_name='ID de Listing Etsy')),
                ('sku', models.CharField(blank=True, help_text='Código SKU del producto', max_length=100, verbose_name='SKU')),
                ('title', models.CharField(help_text='Título del producto', max_length=500, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción del producto', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=10, verbose_name='Precio')),
                ('currency', models.CharField(default='USD', help_text='Código de moneda (USD, EUR, etc.)', max_length=3, verbose_name='Moneda')),
                ('quantity', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Cantidad')),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Cantidad mínima antes de alertar stock bajo', verbose_name='Umbral de Stock Bajo')),
                ('is_active', models.BooleanField(default=True, help_text='Si el producto está activo en Etsy', verbose_name='Activo')),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última sincronización', verbose_name='Última Sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('store', models.ForeignKey(help_text='Tienda a la que pertenece este producto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'etsy_listing_id')},
            },
        ),
    ]
